version: '3'
services:
  mongo:
    container_name: MongoDB
    volumes:
      - 'mongo-data:/data/db'
    image: 'mongo'
    ports:
      - '27017:27017'
  backend:
    container_name: backend
    build: ./backend
    ports:
      - '4000:4000'
    links:
      - mongo
    depends_on:
      - mongo
  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - '3000:3000'
    links:
      - backend
    depends_on:
      - backend
volumes:
  mongo-data:
